ignored = ["github.com/nauqnew/heroes-service/chaincode"]

[[constraint]]
  # Release v1.0.0-alpha5
  name = "github.com/hyperledger/fabric-sdk-go"
  revision = "0e710cebffe5674d411a625bc103ff0e266bb5e1"
